# Generated by Django 4.1 on 2024-03-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DPI", "0003_dpi_document_douane"),
    ]

    operations = [
        migrations.AddField(
            model_name="dpi",
            name="date_facture",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="dpi",
            name="certificat_atestation_don",
            field=models.FileField(
                blank=True, null=True, upload_to="dpi/attestation_don/"
            ),
        ),
        migrations.AlterField(
            model_name="dpi",
            name="document_douane",
            field=models.FileField(
                blank=True, null=True, upload_to="dpi/document_douane/"
            ),
        ),
        migrations.AlterField(
            model_name="dpi",
            name="facture_proforma",
            field=models.FileField(blank=True, null=True, upload_to="dpi/proforma/"),
        ),
    ]
