# Generated by Django 4.1 on 2024-01-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Produit", "0002_produit_demande"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit_demande",
            name="stupefiant",
            field=models.BooleanField(default=False),
        ),
    ]
