# Generated by Django 4.1 on 2024-01-04 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Produit", "0004_devise"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit_demande",
            name="devise",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Produit.devise",
            ),
        ),
    ]
