# Generated by Django 4.1 on 2024-01-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Produit", "0005_produit_demande_devise"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="code_douanier",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
