# Generated by Django 4.1 on 2024-01-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Produit", "0006_produit_code_douanier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produit",
            name="code_douanier",
        ),
        migrations.AddField(
            model_name="produit_demande",
            name="code_douanier",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
