# Generated by Django 4.1 on 2023-12-30 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Demande", "0007_signataire"),
    ]

    operations = [
        migrations.CreateModel(
            name="Objet_demande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=25)),
            ],
            options={
                "verbose_name": "demandeur",
                "verbose_name_plural": "demandeurs",
            },
        ),
        migrations.AlterModelOptions(
            name="nature_impression",
            options={},
        ),
        migrations.AddField(
            model_name="demande",
            name="destinataire",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="demande",
            name="objet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Demande.objet_demande",
            ),
        ),
    ]
