# Generated by Django 4.1 on 2024-01-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Demande", "0008_objet_demande_alter_nature_impression_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Infos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("denomination", models.CharField(max_length=100, null=True)),
                ("sigle", models.CharField(max_length=50, null=True)),
                ("devise", models.CharField(max_length=50, null=True)),
                ("url_base", models.CharField(max_length=50, null=True)),
                ("url_recepice", models.CharField(max_length=50, null=True)),
                ("telephone", models.CharField(max_length=50, null=True)),
                ("email", models.CharField(max_length=50, null=True)),
                ("bp", models.CharField(max_length=50, null=True)),
                ("adresse", models.CharField(max_length=50, null=True)),
                ("lien_facebook", models.TextField(null=True)),
                ("lien_youtube", models.TextField(null=True)),
                ("lien_instagram", models.TextField(null=True)),
                ("lien_linkedil", models.TextField(null=True)),
            ],
        ),
    ]
