# Generated by Django 4.1 on 2024-01-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Demande", "0009_infos"),
    ]

    operations = [
        migrations.AddField(
            model_name="infos",
            name="monaie",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
