# Generated by Django 4.1 on 2024-01-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Demande", "0010_infos_monaie"),
    ]

    operations = [
        migrations.AddField(
            model_name="objet_demande",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
