# Generated by Django 4.1 on 2024-01-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Demande", "0011_objet_demande_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="demande",
            name="note",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="traitement",
            name="utilisateur",
            field=models.TextField(null=True),
        ),
    ]
