# Generated by Django 4.1 on 2024-01-05 20:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Demande", "0012_demande_note_traitement_utilisateur"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="traitement",
            name="type_demande",
        ),
    ]
