# Generated by Django 4.1 on 2024-01-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Demande", "0013_remove_traitement_type_demande"),
    ]

    operations = [
        migrations.AddField(
            model_name="infos",
            name="arrete",
            field=models.TextField(null=True),
        ),
    ]
