# Generated by Django 4.1 on 2024-02-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Demande", "0016_infos_cout_asi"),
    ]

    operations = [
        migrations.AddField(
            model_name="signataire",
            name="titre_honorifique",
            field=models.TextField(null=True),
        ),
    ]
