# Generated by Django 4.1 on 2024-03-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ASE", "0003_ase_nature_impression"),
    ]

    operations = [
        migrations.AddField(
            model_name="ase",
            name="date_facture",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="ase",
            name="copie_asi",
            field=models.FileField(blank=True, null=True, upload_to="ase/copie_asi/"),
        ),
        migrations.AlterField(
            model_name="ase",
            name="facture_proforma",
            field=models.FileField(blank=True, null=True, upload_to="ase/proforma/"),
        ),
    ]
