# Generated by Django 4.1 on 2024-01-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ADI", "0002_adi_nature_impression"),
    ]

    operations = [
        migrations.AddField(
            model_name="adi",
            name="cout",
            field=models.IntegerField(null=True),
        ),
    ]
