# Generated by Django 4.1 on 2024-01-05 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Produit", "0007_remove_produit_code_douanier_and_more"),
        ("ADI", "0003_adi_cout"),
    ]

    operations = [
        migrations.AddField(
            model_name="adi",
            name="devise",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Produit.devise",
            ),
        ),
    ]
