# Generated by Django 4.1 on 2024-03-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ADI", "0004_adi_devise"),
    ]

    operations = [
        migrations.AddField(
            model_name="adi",
            name="date_facture",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="adi",
            name="facture_proforma",
            field=models.FileField(blank=True, null=True, upload_to="adi/proforma/"),
        ),
    ]
