# Generated by Django 4.1 on 2024-01-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ASI", "0012_asi_note_stupefiant"),
    ]

    operations = [
        migrations.AddField(
            model_name="asi",
            name="code_facture",
            field=models.TextField(null=True),
        ),
    ]
