# Generated by Django 4.1 on 2024-02-01 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Demande", "0016_infos_cout_asi"),
        ("ASI", "0013_asi_code_facture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.IntegerField(null=True)),
                ("cout", models.IntegerField(null=True)),
                ("total_item", models.IntegerField(null=True)),
                ("payer", models.BooleanField(default=False)),
                ("num_quittance", models.CharField(max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "demande",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Demande.demande",
                    ),
                ),
            ],
        ),
    ]
