# Generated by Django 4.1 on 2024-02-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ASI", "0014_facture"),
    ]

    operations = [
        migrations.AddField(
            model_name="facture",
            name="code",
            field=models.TextField(null=True),
        ),
    ]
