# Generated by Django 4.1 on 2024-02-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ASI", "0015_facture_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asi",
            name="copie_quittance",
        ),
        migrations.RemoveField(
            model_name="asi",
            name="num_quittance",
        ),
        migrations.AddField(
            model_name="facture",
            name="copie_quittance",
            field=models.TextField(null=True),
        ),
    ]
