# Generated by Django 4.1 on 2024-02-15 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ASI", "0016_remove_asi_copie_quittance_remove_asi_num_quittance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facture",
            name="demande",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="ASI.asi"
            ),
        ),
    ]
