# Generated by Django 4.1 on 2024-02-15 03:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ASI", "0017_alter_facture_demande"),
    ]

    operations = [
        migrations.RenameField(
            model_name="facture",
            old_name="demande",
            new_name="asi",
        ),
    ]
