# Generated by Django 4.1 on 2024-02-15 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ASI", "0019_group_facture_facture_group_facture"),
    ]

    operations = [
        migrations.AddField(
            model_name="group_facture",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="group_facture",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
