# Generated by Django 4.1 on 2024-02-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ASI", "0021_group_facture_num_quittance_group_facture_structure"),
    ]

    operations = [
        migrations.AddField(
            model_name="group_facture",
            name="payer",
            field=models.BooleanField(default=False),
        ),
    ]
