# Generated by Django 4.1 on 2024-03-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ASI", "0022_group_facture_payer"),
    ]

    operations = [
        migrations.AddField(
            model_name="asi",
            name="date_facture",
            field=models.DateField(null=True),
        ),
    ]
