# Generated by Django 4.1 on 2024-03-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ASI", "0023_asi_date_facture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asi",
            name="certicat_bonne_pratique",
            field=models.FileField(
                blank=True, null=True, upload_to="asi/cert_bonne_pratiq/"
            ),
        ),
        migrations.AlterField(
            model_name="asi",
            name="certificat_analyse_prod",
            field=models.FileField(
                blank=True, null=True, upload_to="asi/certificat_analyse_prod/"
            ),
        ),
        migrations.AlterField(
            model_name="asi",
            name="certificat_atestation_don",
            field=models.FileField(
                blank=True, null=True, upload_to="asi/cert_attestation_don/"
            ),
        ),
        migrations.AlterField(
            model_name="asi",
            name="certificat_origine_prod",
            field=models.FileField(
                blank=True, null=True, upload_to="asi/cert_origine_prod/"
            ),
        ),
        migrations.AlterField(
            model_name="asi",
            name="facture_proforma",
            field=models.FileField(blank=True, null=True, upload_to="asi/proforma/"),
        ),
    ]
