# Generated by Django 4.1 on 2024-01-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Demandeur", "0002_remove_demandeur_ville_demandeur_adresse_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Structure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("denomination", models.CharField(max_length=50, null=True)),
                ("telephone", models.CharField(max_length=20, null=True)),
                ("email", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
