# Generated by Django 4.1 on 2024-01-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Demandeur", "0003_structure"),
    ]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="grossiste",
            field=models.BooleanField(default=False),
        ),
    ]
